language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -f Dockerfile.dev -t bigodinho22/docker-course . 
script:
    - docker run bigodinho22/docker-course npm run test -- --coverage