language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -f Dockerfile.dev -t bigodinho22/docker-course . 
script:
    - docker run -e CI=true bigodinho22/docker-course npm run test
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-course"
    env: "DockerCourse-env"
    bucket_name: "elasticbeanstalk-us-east-2-536180565663"
    bucket_path: "docker-course"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"